FIN-29: Init commit
valitydev/dominator-proto pull request #1
Opened 2024-04-25 13:38 UTC by D-Baykov

2024-04-25 15:08 UTC, ggmaleva commented on proto/dominator.thrift
> +include "proto/base.thrift"
это damsel? Мы разве не хоти отвязаться от него? Как я понимаю планируется, что тут же в перспективе будут и данные GE по ставкам.

2024-04-25 15:08 UTC, ggmaleva commented on rebar.config
> +%% Common project erlang options.
а нам нужно для erlang собирать протокол? тут вроде только java и фронт, разве нет?

2024-04-25 15:08 UTC, ggmaleva commented on proto/dominator.thrift
> +struct ShopsSearchQuery {
Как я понял, структура подобная magista. Такой формат удобен фронту? Мб добавить все-таки комментов, как работают эти запросы?

2024-04-25 15:08 UTC, ggmaleva commented on proto/dominator.thrift
> +    2: required domain.ShopID shop_id
Если этот ответ выдается и кошелькам, где тогда кошелек или identity, к которому termSet привязан? Я же правильно понял, что Term это termSet?

2024-04-25 15:08 UTC, ggmaleva commented on proto/dominator.thrift
> +struct Term {
мб назвать TermSet назвать, чтобы не путаться?

2024-04-25 15:08 UTC, ggmaleva commented on proto/dominator.thrift
> +    TermsResponse SearchShopTerms (1: ShopsSearchQuery shops_search_query)
мб и в методах ...TermSets назвать?

2024-04-25 15:08 UTC, ggmaleva commented on proto/dominator.thrift
> +    5: required string term_name
term_set_name ?

2024-04-25 15:08 UTC, ggmaleva commented on proto/dominator.thrift
> +    6: required domain.TermSetHierarchyObject current_term
current_term_set

2024-04-25 15:08 UTC, ggmaleva commented on proto/dominator.thrift
> +    7: optional list<domain.TermSetHierarchyObject> term_history
term_set_history

2024-04-25 15:08 UTC, ggmaleva commented on proto/dominator.thrift
> +    3: optional list<string> term_names
term_set_names

2024-04-25 15:08 UTC, ggmaleva commented on proto/dominator.thrift
> +    3: optional list<string> term_names
term_set_names

2024-04-25 15:08 UTC, ggmaleva commented on proto/dominator.thrift
> +struct CommonSearchQueryParams {
лучше это вынести перед запросами, чтобы удобнее было читать протокол

2024-04-25 15:08 UTC, ggmaleva commented on proto/dominator.thrift
> +struct Term {
и их лучше поднять над Response для удобства чтения

2024-04-25 15:08 UTC, ggmaleva commented on proto/dominator.thrift
> +    1: required domain.PartyID party_id
разве оно должно быть обязательным? у терминалов  вообще party нет.

2024-04-25 15:38 UTC, D-Baykov commented on proto/dominator.thrift
> +struct ShopsSearchQuery {
Подобно магисте в плане протокола, а не подробностей

2024-04-25 15:40 UTC, D-Baykov commented on proto/dominator.thrift
> +include "proto/base.thrift"
Впервые слышу про отвязку от дамзели

2024-04-25 15:42 UTC, D-Baykov commented on rebar.config
> +%% Common project erlang options.
Сделал аналогично магисте. Если не надо будет можно выпилить в будущем (тут для эрланга минимум кода)

2024-04-25 15:47 UTC, D-Baykov commented on proto/dominator.thrift
> +    2: required domain.ShopID shop_id
Это обертка над термсетом, да. Айдентити добавлю

2024-04-25 15:48 UTC, D-Baykov commented on proto/dominator.thrift
> +struct Term {
Это не совсем термсет. Если это структуру ТермСет назвать, то тогда она точно будет путать

2024-04-25 15:52 UTC, D-Baykov commented on proto/dominator.thrift
> +struct CommonSearchQueryParams {
Никогда не понимал такое написание, когда сам интересующий контекст в самом низу

2024-04-25 15:53 UTC, D-Baykov commented on proto/dominator.thrift
> +struct Term {
Категорически не согласен с тем, что так читать удобнее

2024-04-25 15:59 UTC, D-Baykov commented on proto/dominator.thrift
> +struct Term {
Но от нас так везде в протоколах - поправил

2024-04-25 17:22 UTC, ggmaleva commented on proto/dominator.thrift
> +struct Term {
Это и не Term (что это вообще значит?). Кажется, тут нужно название понятнее.

2024-04-25 17:25 UTC, ggmaleva commented on proto/dominator.thrift
> +include "proto/base.thrift"
Я бы сразу это обсудил. Для общего понимания.

2024-04-26 08:40 UTC, ggmaleva commented on proto/dominator.thrift
> +include "proto/base.thrift"
тут прояснил, откидываю вопрос)

2024-04-26 08:41 UTC, ggmaleva commented on proto/dominator.thrift
> +struct ShopsSearchQuery {
Но комменты имхо лучше добавить, после того как с Ринатом обговоришь)

2024-04-26 08:43 UTC, ggmaleva commented
Мне кажется следует как-то переименовать попонятнее все, что связано с termSet)

2024-04-26 10:22 UTC, ggmaleva submitted a review, later dismissed
Так выглядит лучше)

2024-04-26 11:52 UTC, A77AY requested changes

2024-04-26 11:52 UTC, A77AY commented on package.json
> +  "version": "2.0.1",
```suggestion
  "version": "1.0.0",
```

2024-04-26 11:52 UTC, A77AY commented on package-lock.json
> +  "version": "2.0.1",
```suggestion
  "version": "1.0.0",
```

2024-04-26 11:52 UTC, A77AY commented on proto/dominator.thrift
> +    2: required domain.PartyID party_id
А paty id будет обязательным?

2024-04-26 11:52 UTC, A77AY commented on proto/dominator.thrift
> +}
У терминала нет TermSetHierarchyObject?

2024-04-26 11:52 UTC, A77AY commented on proto/dominator.thrift
> +    4: optional list<string> term_sets_names
как будто имеет смысл еще и по ids фильтровать

2024-04-26 11:52 UTC, A77AY commented on proto/dominator.thrift
> +    4: optional list<string> term_sets_names
names не уникальный и конкретные мы получить не сможем сейчас

2024-04-26 11:52 UTC, A77AY commented on proto/dominator.thrift
> +    3: required string provider
скорее всего должен быть id и name отдельно

2024-04-26 11:52 UTC, A77AY commented on proto/dominator.thrift
> +}
у нас есть фильтр по currencies выглядит так что он должен быть и в результатах

2024-04-26 11:52 UTC, A77AY commented on proto/dominator.thrift
> +struct TermSet {
выглядит так что надо на 2 оъекта поделить WalletTermSet и ShopTermSet, тут есть свойства shop_id, shop_name

2024-04-26 11:52 UTC, A77AY commented on proto/dominator.thrift
> +    3: optional list<base.ID> identity_ids
думаю нужен еще wallet ids

2024-04-26 12:33 UTC, D-Baykov commented on proto/dominator.thrift
> +    2: required domain.PartyID party_id
думаю можно и без него (только по шопу, например) искать. Уберу

2024-04-26 12:39 UTC, D-Baykov commented on proto/dominator.thrift
> +}
Согласно протоколу так и альтернатив не видно https://github.com/valitydev/damsel/blob/master/proto/domain.thrift#L2552

2024-04-26 12:52 UTC, D-Baykov commented on proto/dominator.thrift
> +    3: optional list<base.ID> identity_ids
так как везде нужны ids вынесу это в common_search_query_params

2024-04-26 12:56 UTC, A77AY commented on proto/dominator.thrift
> +    3: optional list<base.ID> identity_ids
для терминалов же там Ref вроде

2024-04-26 12:59 UTC, A77AY commented on proto/dominator.thrift
> +}
так же основной объект TermSetHierarchyObject и ты из него уже достаешь Terminal?

2024-04-26 13:00 UTC, A77AY commented on proto/dominator.thrift
> +    2: required domain.PartyID party_id
так то нужен будет думаю, в будущем попросят, просто optional

2024-04-26 13:09 UTC, A77AY commented on proto/dominator.thrift
> +struct WalletTermSet {
по аналогии с Shop думаю нужно добавить wallet id и name..

2024-04-26 13:12 UTC, A77AY commented on proto/dominator.thrift
> +    3: optional list<base.ID> identity_ids
у wallet есть и identity id и wallet id

2024-04-26 13:23 UTC, D-Baykov commented on proto/dominator.thrift
> +}
А где в TermSetHierarchyObject терминал? 
Вот список того, что в нем есть (поправь, если я что-то проглядел)
https://github.com/valitydev/damsel/blob/master/proto/domain.thrift#L1155

2024-04-26 13:26 UTC, A77AY commented on proto/dominator.thrift
> +}
хмм, я думал через него, тогда выглядит ок

2024-04-26 13:50 UTC, A77AY approved these changes

2024-04-26 13:51 UTC, merged